apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for deploying alert2omi bridge in Openshift
    iconClass: icon-python
    name: alert2omi
  labels:
    template: alert2omi-template
  name: alert2omi-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        nodeSelector:
          environment: prod 
          region: infra
        containers:
        - image: alert2omi:latest
          name: alert2omi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - alert2omi
        from:
          kind: ImageStreamTag
          name: alert2omi:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APP_NAME
  required: true
  value: alert2omi
